### ISSUE TITLE
Implement Carlisle's method for baseline measurement comparison

### ISSUE THREAD

**Issue by chartgerink** [chartgerink/2017ctgov#2]
Implement an R function (other languages welcome as well!) where the method to compare baseline measurements are implemented. All relevant files stored in the `functions/` folder.

# Tasks

TBD

# Papers
1. [10.1111/j.1365-2044.2012.07128.x](https://doi.org/10.1111/j.1365-2044.2012.07128.x) (paywalled though... [E-mail me](mailto:chjh@protonmail.com) if you want a copy! [I am not allowed to share on here due to copyright]) 

2. [10.1111/anae.13126](https://doi.org/10.1111/anae.13126) (also paywalled; same applies: [e-mail me](mailto:chjh@protonmail.com) for a copy!)

**Comment by chartgerink** [comment]
Oh and this article is the previous attempt at funding where we describe some of the methods incompletely, but which is open access.

[http://riojournal.com/articles.php?id=7462](http://riojournal.com/articles.php?id=7462)

**Comment by chartgerink** [comment]
Okay so here's what needs to be done for implementation:

- [ ] Normalize continuous variables
	- [x] Means
	- [ ] Proportions
- [ ] Compute deviation from expected
	- [x] Count variables
	- [x] Means
	- [ ] Proportion
- [ ] Create a function that computes chi-squared test given a tidy dataset
- [x] Create an implementation of function above specific for this CTgov data

Any code contributions for functions please added in `functions/rct_baseline.R`. Implementation in `functions/xml_parsing.R`.
