### ISSUE TITLE
Create network graph of flagged trials

### ISSUE THREAD

**Issue by chartgerink** [chartgerink/2017ctgov#4]
The flagged trials can be mapped to a network of outputs, funders, etc. This issue is to discuss everything that comes to analyzing the data from ClinicalTrials and the linked outputs from PMC.

# Tasks

- [ ] How to create the network easily and reproducible
- [ ] How to setup data in such a way that networks can be actually computed
- [ ] What variables are of relevance to create the network?
- [ ] What outcome measures are useful for the networks?

I have little knowledge about network analysis so help here is even more greatly appreciated than help on the other issues ;-)
